# Give the kit pages some text a crawler can actually read.
#
# The problem. Every kit here is a single-file JS app: the HTML ships an empty
# container and the app fills it on load. Great for users, invisible to a
# crawler that reads the HTML. Measured 2026-08-11, sixteen URLs that are IN the
# sitemap shipped under ~250 characters of readable text each: projects/ 59,
# sql/ 153, powerbi/ 155. The median guide page is 18,706. Google fetches those
# sixteen, finds nothing worth keeping, and files them under "Crawled, currently
# not indexed", which is exactly what Search Console was reporting.
#
# The fix. A visible "About this kit" section appended near the end of <body>,
# before apk-footer.js appends the book card and the footer. It is real content
# in the HTML, so a crawler gets it on the first fetch with no rendering.
#
# Why it is VISIBLE and not hidden. Text served to crawlers and hidden from
# people is cloaking, and it is the kind of thing that gets a site demoted
# rather than promoted. This block is plain, honest orientation that a first
# time visitor genuinely benefits from, sitting at the bottom where it does not
# cover the app. Do not "optimise" it by hiding it on arrival.
#
# It IS taken off the other screens (Mike, 2026-08-11: "that text does not need
# to be on every screen/lesson card in the kit"). The block lives at the end of
# <body>, outside the app's container, so it survived every re-render and sat
# under every lesson, drill and settings page as furniture. TOGGLE below hides
# it once the visitor navigates off the landing screen and brings it back when
# they return. That is not the hidden-text trick: nothing is served to a crawler
# that a person on the same URL does not see. The page as fetched shows it,
# unhidden, with no interaction and no script needed to reveal it.
#
# Why not inject into the app's own container. Three different shells are in use
# here (<main id="main">, <div id="app">, and the view-* pages), each wiped at a
# different moment, so injecting inside them means sixteen chances to break a
# working app for a text gain we can get safely at the end of the body.
#
# Idempotent: the block sits between sentinel comments and is replaced whole on
# a re-run. Edit KITS below and run again.
#
# Usage:
#     python tools/build-kit-seo.py
#     python tools/build-kit-seo.py --dry-run
#
# Reads and writes UTF-8 with no BOM and preserves existing line endings, so it
# does not do to these files what PowerShell's Set-Content does.

import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

START = "<!-- APK:KIT-SEO:START (generated by tools/build-kit-seo.py, do not hand-edit) -->"
END = "<!-- APK:KIT-SEO:END -->"

# Styling leans on each kit's own theme vars with a light fallback, the same
# trick apk-footer.js uses, so the block reads correctly in dark and light.
CSS = """<style>
.apk-about{max-width:760px;margin:44px auto 0;padding:0 22px;font-family:inherit;
  font-size:15px;line-height:1.7;color:var(--muted,#555);text-align:left}
.apk-about h2{font-size:19px;margin:0 0 10px;color:var(--text,inherit)}
.apk-about h3{font-size:15px;margin:22px 0 6px;color:var(--text,inherit)}
.apk-about p{margin:0 0 12px}
.apk-about ul{margin:0 0 12px;padding-left:20px}
.apk-about li{margin:3px 0}
.apk-about a{color:var(--accent,#C5511F);text-decoration:none}
.apk-about a:hover{text-decoration:underline}
.apk-about[hidden]{display:none}
</style>"""

# Landing-screen only. Four shells are in use across these sixteen pages and
# each names its current screen differently, so the check walks them in order
# and stops at the first one the page actually has:
#
#   .view.active         stats, tableau, chart-literacy, forecasting, interview
#   currentView          sql, powerbi
#   VIEW.name            projects
#   state.view           final, and the five cert kits
#
# A page with none of them (viz, simulator) has no second screen to be wrong on,
# so it keeps the block up. Those globals are top-level `let`/`const` in each
# kit's own classic script, which puts them in the same global lexical scope
# this script reads, hence the bare identifiers and the try/except-style guards.
#
# The observer watches childList only, so setting `hidden` (an attribute) cannot
# retrigger it, and the value guard makes a loop impossible either way.
SCRIPT = """<script>
(function(){
  var about=document.querySelector('.apk-about');
  if(!about) return;
  function onLanding(){
    var v=document.querySelector('.view.active');
    if(v) return v.id==='view-home';
    try{ if(typeof currentView==='string') return currentView==='home'; }catch(e){}
    try{ if(typeof VIEW==='object'&&VIEW&&VIEW.name) return VIEW.name==='home'; }catch(e){}
    try{ if(typeof state==='object'&&state&&typeof state.view==='string') return state.view==='home'; }catch(e){}
    return true;
  }
  function sync(){ var h=!onLanding(); if(about.hidden!==h) about.hidden=h; }
  var t;
  new MutationObserver(function(){ clearTimeout(t); t=setTimeout(sync,60); })
    .observe(document.body,{childList:true,subtree:true});
  window.addEventListener('hashchange',sync);
  sync();
})();
</script>"""

# Every claim below was read off the page it describes on 2026-08-11: the unit
# names come from each kit's own DATA, the counts from its meta description.
# If a kit gains a unit, update it here rather than inventing a nicer number.
KITS = {
    "sql": {
        "h": "About the SQL Kit",
        "p": [
            "A free, in-browser course in SQL for people moving into data work. Queries run for real against a live database in the page, so nothing needs installing and there is no account to make before you start.",
            "It runs from what a table is through to the joins and window functions that interviews actually ask about. Forty-six practice problems, each with the answer and the reason it is right.",
        ],
        "units": ["Orientation, and what a database really is", "First queries: SELECT, WHERE, ORDER BY",
                  "Aggregation and shaping with GROUP BY", "Joins, and why totals move when you add one",
                  "Advanced SQL: CTEs, subqueries, window functions", "Data migration work",
                  "From a question to a metric", "Financial analysis", "The advanced analyst toolkit"],
        "guides": [("set-up-a-sql-database", "Set up a SQL database in fifteen minutes"),
                   ("sql-foundations", "SQL foundations"), ("sql-joins", "SQL JOINs"),
                   ("sql-group-by-having", "GROUP BY and HAVING"), ("sql-ctes", "SQL CTEs"),
                   ("sql-window-functions", "Window functions"), ("sql-comments", "How to comment in SQL")],
    },
    "powerbi": {
        "h": "About the Power BI Kit",
        "p": [
            "A free, in-browser introduction to Power BI that needs no install. Power BI Desktop is Windows only and a large download, so this kit teaches the model and the language first, in a form you can work through on any machine.",
            "The order is deliberate. Most Power BI trouble is not the buttons, it is a data model that was never shaped properly, so the star schema and the difference between a measure and a column come before the visuals.",
        ],
        "units": ["Before you build: shaping the question", "The interface and the data",
                  "DAX and measures", "Reports and insights", "Data migration work",
                  "From a question to a metric", "Financial analysis", "The advanced analyst toolkit"],
        "guides": [("install-power-bi-desktop", "Install Power BI Desktop"),
                   ("import-a-csv-into-power-bi", "Import a CSV into Power BI"),
                   ("powerbi-star-schema", "The star schema"),
                   ("powerbi-measures-vs-columns", "Measures vs calculated columns"),
                   ("powerbi-calculate", "CALCULATE"),
                   ("powerbi-time-intelligence", "Time intelligence")],
    },
    "stats": {
        "h": "About the Statistics Kit",
        "p": [
            "Thirty-six lessons on the statistics an analyst is actually asked for, with interactive visuals you can push around rather than formulas to memorise.",
            "It is built around the questions that arrive in the job. Is this gap real or noise. Which average should I be quoting. How confident am I allowed to sound about this. The maths is there, but it always follows the question.",
        ],
        "units": ["Describing data: centre, spread and shape", "Distributions and what they imply",
                  "Sampling, uncertainty and confidence", "Testing whether a difference is real",
                  "Relationships between variables", "Presenting a statistical result honestly"],
        "guides": [("mean-vs-median", "Mean vs median"), ("standard-deviation", "Standard deviation"),
                   ("percentiles-iqr-outliers", "Percentiles, IQR and outliers"),
                   ("confidence-intervals", "Confidence intervals"), ("p-values", "P-values"),
                   ("ab-testing-for-analysts", "A/B testing for analysts"),
                   ("correlation-vs-causation", "Correlation vs causation")],
    },
    "tableau": {
        "h": "About the Tableau Kit",
        "p": [
            "Free in-browser practice for Tableau, covering both everyday dashboard work and the ground the Tableau Desktop Foundations certification tests.",
            "Tableau is quick to make a chart in and slow to make a correct one in. The kit spends its time on the parts that decide whether two sheets on the same data agree: relationships, level of detail, and what a filter is really doing.",
        ],
        "units": ["Before you build: foundations", "Tableau fundamentals",
                  "Building better vizzes", "Dashboards and best practice",
                  "Connecting and preparing data", "Sets, hierarchies, parameters and dual axis"],
        "guides": [("install-tableau-public", "Install Tableau Public"),
                   ("connect-tableau-to-your-data", "Connect Tableau to your data"),
                   ("tableau-concepts", "Core Tableau concepts"),
                   ("tableau-relationships", "Tableau relationships"),
                   ("build-a-tableau-dashboard", "Build a Tableau dashboard and story"),
                   ("tableau-sheets-to-dashboard", "From sheets to a dashboard")],
    },
    "forecasting": {
        "h": "About the Forecasting Kit",
        "p": [
            "Time-series forecasting for analysts, from a moving average through to stating what a forecast cannot tell you.",
            "The last unit is the one most courses skip and most jobs need. A forecast that arrives without its error range is a guess wearing a chart, and being able to say how far ahead you are willing to commit is the part people remember.",
        ],
        "units": ["Foundations: what a time series is", "Trend and smoothing",
                  "Forecasting models", "Evaluating a forecast and communicating it"],
        "guides": [("moving-averages", "Moving averages"), ("forecast-accuracy", "Forecast accuracy"),
                   ("correlation-vs-causation", "Correlation vs causation"),
                   ("documenting-data-limitations", "Documenting data limitations")],
    },
    "chart-literacy": {
        "h": "About the Chart Literacy Kit",
        "p": [
            "Reading, choosing and explaining charts, which is the visual half of nearly every analyst and BI job and the half that rarely gets taught.",
            "Two units are about making charts and two are about not being fooled by them. Knowing how a chart misleads is what lets you catch it in someone else's deck, and in your own.",
        ],
        "units": ["How charts work", "The charts you will use most",
                  "How charts mislead", "Choosing a chart and communicating it"],
        "guides": [("choose-the-right-chart", "Choose the right chart"),
                   ("how-charts-mislead", "How charts mislead"),
                   ("excel-pick-the-chart", "Pick the chart in Excel"),
                   ("excel-sort-your-bars", "Sort your bars"),
                   ("excel-chart-design-basics", "Chart design basics")],
    },
    "interview": {
        "h": "About Interview Prep",
        "p": [
            "Timed mock interviews for data analyst roles, with questions drawn from real screens across SQL, Excel, Power BI and the reasoning questions that sit between them.",
            "The gap it targets is a specific one. Plenty of people can do the work and then lose the room trying to describe it in ninety seconds. This is practice at saying it out loud, under a clock.",
        ],
        "units": ["Technical questions across SQL, Excel and BI tools",
                  "Reasoning and judgment questions", "Timed practice with feedback",
                  "Talking through your own portfolio work"],
        "guides": [("technical-tenacity", "Technical tenacity"),
                   ("report-vs-analysis", "Report vs analysis"),
                   ("defining-metrics", "Defining a metric"),
                   ("choose-your-analyst-role", "Choose your analyst role"),
                   ("what-is-data-analysis", "What data analysis actually is")],
    },
    "viz": {
        "h": "About Viz Drill",
        "p": [
            "Drag fields onto shelves and build the chart that answers a question, one new idea per step. It is the Tableau motion without the Tableau install.",
            "Two tracks. One uses data small enough to check by eye, so you can see whether the chart is telling the truth. The other uses the 7,043 customers behind a published churn analysis, which is large enough that you have to trust the chart instead.",
        ],
        "units": ["Dimensions, measures and what goes where",
                  "Building a chart that answers a stated question",
                  "A small track you can verify by eye",
                  "A real track: 7,043 customers of churn data"],
        "guides": [("choose-the-right-chart", "Choose the right chart"),
                   ("build-a-tableau-dashboard", "Build a Tableau dashboard and story"),
                   ("tableau-sheets-to-dashboard", "From sheets to a dashboard"),
                   ("how-charts-mislead", "How charts mislead")],
    },
    "projects": {
        "h": "About Project Studio",
        "p": [
            "A guided route through building a portfolio project, from scoping a question to presenting what you found. Excel, SQL and Tableau first, because those are what job adverts ask for most.",
            "It follows the stages a real analysis moves through rather than a tool tutorial, since the common portfolio failure is not a missing skill. It is a finished project that its own author cannot explain the point of.",
        ],
        "units": ["Scoping a question worth answering", "Finding and profiling the data",
                  "The analysis itself", "Writing up what you found",
                  "Presenting it, including what the data could not settle"],
        "guides": [("what-is-data-analysis", "What data analysis actually is"),
                   ("free-datasets-to-practice-with", "Free datasets to practice with"),
                   ("exploratory-data-analysis", "Exploratory data analysis"),
                   ("defining-metrics", "Defining a metric"),
                   ("documenting-data-limitations", "Documenting data limitations"),
                   ("report-vs-analysis", "Report vs analysis")],
    },
    "simulator": {
        "h": "About the Associate Data Analyst Simulator",
        "p": [
            "A simulated first week as an associate data analyst at a fictional firm, DataBridge Analytics. Five days, ten assignments, each one reviewed the way a manager would review it.",
            "The work is deliberately shaped like real work rather than like exercises: requests that arrive half specified, data that does not quite match what you were told, and the need to say what you did and why.",
        ],
        "units": ["Five simulated days", "Ten assignments with a business request behind each",
                  "Manager review on every submission",
                  "Practice at writing up a result for someone who is not an analyst"],
        "guides": [("report-vs-analysis", "Report vs analysis"),
                   ("defining-metrics", "Defining a metric"),
                   ("documenting-data-limitations", "Documenting data limitations"),
                   ("technical-tenacity", "Technical tenacity"),
                   ("verify-ai-agent-work", "Verifying AI agent work")],
    },
    "final": {
        "h": "About the Final Exam Kit",
        "p": [
            "A twenty-eight question exam across everything the Analyst Prep Kit covers: Excel, SQL, Python, Tableau, statistics, Power BI and the interview essentials.",
            "It ships with a study guide holding the bare basics of each area, so a wrong answer has somewhere to send you rather than just being marked wrong.",
        ],
        "units": ["Excel", "SQL", "Python", "Tableau", "Statistics", "Power BI", "Interview essentials"],
        "guides": [("sql-foundations", "SQL foundations"), ("excel-pivot-tables", "Excel pivot tables"),
                   ("pandas-groupby", "pandas groupby"), ("tableau-concepts", "Core Tableau concepts"),
                   ("mean-vs-median", "Mean vs median"),
                   ("powerbi-measures-vs-columns", "Measures vs calculated columns")],
    },
    "excel-cert": {
        "h": "About Excel Certification Prep (MO-210)",
        "p": [
            "Free preparation for the Microsoft Office Specialist Excel Associate certification, exam code MO-210. A study guide covering all five objective domains, plus a thirty-five question practice drill.",
            "MO-210 is a performance exam, so it asks you to do things rather than recognise them. The study guide is organised by Microsoft's published domains so you can see which areas you are still weak in.",
        ],
        "units": ["Manage worksheets and workbooks", "Manage data cells and ranges",
                  "Manage tables and table data", "Perform operations using formulas and functions",
                  "Manage charts"],
        "guides": [("excel-tables", "Excel tables"), ("excel-pivot-tables", "Pivot tables"),
                   ("excel-if-family", "The IF family"), ("excel-index-match", "INDEX and MATCH"),
                   ("excel-conditional-formatting", "Conditional formatting"),
                   ("excel-custom-number-formats", "Custom number formats")],
    },
    "tableau-cert": {
        "h": "About Tableau Certification Prep",
        "p": [
            "Preparation for the Salesforce Certified Tableau Desktop Foundations exam, previously called Tableau Desktop Specialist. A study guide organised by exam domain, plus a full fifty-three question practice exam.",
            "The domains are weighted unevenly, so the guide says how much of the exam each area is worth. That is usually the difference between revising broadly and revising where the marks are.",
        ],
        "units": ["Connecting to and preparing data", "Exploring and analysing data",
                  "Sharing insights", "Understanding Tableau concepts"],
        "guides": [("tableau-desktop-foundations-exam", "The Tableau Desktop Foundations exam"),
                   ("tableau-concepts", "Core Tableau concepts"),
                   ("tableau-relationships", "Tableau relationships"),
                   ("tableau-hierarchies", "Tableau hierarchies"),
                   ("tableau-sorts", "Sorting in Tableau"),
                   ("tableau-aliases", "Tableau aliases")],
    },
    "powerbi-cert": {
        "h": "About Power BI Certification Prep (PL-300)",
        "p": [
            "Free preparation for the Microsoft PL-300 Power BI Data Analyst certification. A study guide across all four blueprint domains, plus a full fifty question, hundred minute practice exam.",
            "PL-300 leans harder on modelling than most people expect. Preparing mostly on visuals is the common way to fail it, so the model and DAX domains get the most room here.",
        ],
        "units": ["Prepare the data", "Model the data",
                  "Visualise and analyse the data", "Manage and secure Power BI"],
        "guides": [("powerbi-star-schema", "The star schema"),
                   ("powerbi-measures-vs-columns", "Measures vs calculated columns"),
                   ("powerbi-calculate", "CALCULATE"),
                   ("powerbi-time-intelligence", "Time intelligence"),
                   ("powerbi-row-level-security", "Row level security"),
                   ("powerbi-sum-vs-sumx", "SUM vs SUMX")],
    },
    "docusign-cert": {
        "h": "About Docusign eSignature Administration Pro Prep",
        "p": [
            "Preparation for the Docusign eSignature Administration Pro exam, the entry level Docusign administrator credential. An area by area study guide of the settings the exam actually tests.",
            "It is organised around the admin console itself rather than around the marketing names for features, because the exam asks where a setting lives and what turning it on does.",
        ],
        "units": ["Account and user administration", "Templates, envelopes and sending settings",
                  "Branding and signing experience", "Security, authentication and compliance",
                  "Reporting and troubleshooting"],
        "guides": [("docusign-clm-cert", "Docusign CLM Administration Pro prep", "../"),
                   ("what-is-data-analysis", "What data analysis actually is"),
                   ("technical-tenacity", "Technical tenacity")],
    },
    "docusign-clm-cert": {
        "h": "About Docusign CLM Administration Pro Prep",
        "p": [
            "Preparation for the Docusign CLM Administration Pro exam, covering contract lifecycle management administration rather than eSignature.",
            "The guide walks the CLM admin console area by area: folder security, permission profiles, workflow and the service limits that the exam likes to ask precise numbers about.",
        ],
        "units": ["The CLM admin console", "Folder structure and security",
                  "Permission profiles and groups", "Workflow and document generation",
                  "Service limits and troubleshooting"],
        "guides": [("docusign-cert", "Docusign eSignature Administration Pro prep", "../"),
                   ("what-is-data-analysis", "What data analysis actually is"),
                   ("technical-tenacity", "Technical tenacity")],
    },
}


def block_for(slug, kit):
    """Build the static section for one kit."""
    out = [START, CSS, '<section class="apk-about">', f'  <h2>{kit["h"]}</h2>']
    for para in kit["p"]:
        out.append(f"  <p>{para}</p>")

    out.append("  <h3>What is inside</h3>")
    out.append("  <ul>")
    for u in kit["units"]:
        out.append(f"    <li>{u}</li>")
    out.append("  </ul>")

    out.append("  <h3>Related guides</h3>")
    out.append("  <ul>")
    for g in kit["guides"]:
        gslug, label = g[0], g[1]
        prefix = g[2] if len(g) > 2 else "../guides/"
        out.append(f'    <li><a href="{prefix}{gslug}/">{label}</a></li>')
    out.append("  </ul>")

    out.append('  <p><a href="../guides/">Browse all guides</a> · <a href="../">All kits</a></p>')
    out.append("</section>")
    out.append(SCRIPT)
    out.append(END)
    return "\n".join(out)


def main():
    dry = "--dry-run" in sys.argv
    changed = skipped = 0

    for slug, kit in KITS.items():
        path = os.path.join(ROOT, slug, "index.html")
        if not os.path.exists(path):
            print(f"  MISS  {slug}/index.html not found")
            continue

        with io.open(path, encoding="utf-8", newline="") as f:
            html = f.read()

        nl = "\r\n" if "\r\n" in html else "\n"
        block = block_for(slug, kit).replace("\n", nl)

        if START in html:
            new = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda m: block, html, flags=re.S)
            action = "update"
        else:
            m = re.search(r"</body>", html, re.I)
            if not m:
                print(f"  WARN  {slug}/ has no </body>, skipped")
                continue
            new = html[: m.start()] + block + nl + html[m.start():]
            action = "insert"

        if new == html:
            skipped += 1
            print(f"  ok    {slug}/ already current")
            continue

        # Report the readable-text gain, which is the entire point of the file.
        def text_len(h):
            b = re.sub(r"<script.*?</script>|<style.*?</style>|<!--.*?-->", "", h, flags=re.S)
            return len(re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", b)).strip())

        before, after = text_len(html), text_len(new)
        print(f"  {action.upper():<6} {slug + '/':<20} {before:>5} -> {after:>5} chars")

        if not dry:
            with io.open(path, "w", encoding="utf-8", newline="") as f:
                f.write(new)
        changed += 1

    print(f"\n{changed} page(s) {'would change' if dry else 'written'}, {skipped} already current")
    if changed and not dry:
        print("Next: node tools/build-guide-index.js is NOT needed here, but do commit and push.")


if __name__ == "__main__":
    main()
